
<!-- Posts global post-footer -->

<div id="post_composer_messages" style="display: none">
    <div class="tinymce">
        <div class="youtube_embedder">
            <div class="title"><?= $this_module->language->tinymce->youtube_embedder->title ?></div>
            <div class="caption"><?= $this_module->language->tinymce->youtube_embedder->caption ?></div>
            <div class="invalid_link"><?= $this_module->language->tinymce->youtube_embedder->invalid_link ?></div>
        </div>
    </div>
</div>
